from __future__ import annotations

import argparse
import csv
from pathlib import Path

import mujoco
import numpy as np

from hopf_cpg import DEFAULT_AJOINT_DEG, HopfCPG, HopfCPGParams, amp_scales_to_mu_scales, degrees_to_radians


def parse_float_list(value: str, expected_len: int, name: str) -> tuple[float, ...]:
    parts = [part.strip() for part in value.split(",") if part.strip()]
    if len(parts) != expected_len:
        raise argparse.ArgumentTypeError(f"{name} needs {expected_len} comma-separated values")
    return tuple(float(part) for part in parts)


def parse_args():
    parser = argparse.ArgumentParser(description="Measure tethered eel force under a travelling-wave command.")
    parser.add_argument("--xml", default="eel_tethered.xml")
    parser.add_argument("--seconds", type=float, default=6.0)
    parser.add_argument("--skip-seconds", type=float, default=1.0)
    parser.add_argument("--ajoint", "--amp", dest="ajoint", type=float, default=DEFAULT_AJOINT_DEG, help="Base joint angle amplitude in degrees.")
    parser.add_argument("--freq", type=float, default=1.0)
    parser.add_argument("--wavelength", type=float, default=1.5)
    parser.add_argument(
        "--amp-scales",
        type=lambda value: parse_float_list(value, 6, "amp-scales"),
        default=None,
        help="Six comma-separated per-servo amplitude multipliers, e.g. 0.7,0.8,0.9,1.0,1.0,0.9",
    )
    parser.add_argument(
        "--phase-lags",
        type=lambda value: parse_float_list(value, 5, "phase-lags"),
        default=None,
        help="Five comma-separated phase lags between neighboring servos in radians.",
    )
    parser.add_argument("--fb-phase", type=float, default=0.0)
    parser.add_argument("--fb-amp", type=float, default=0.0)
    parser.add_argument("--csv", type=Path, default=None)
    return parser.parse_args()


def main():
    args = parse_args()
    model = mujoco.MjModel.from_xml_path(args.xml)
    data = mujoco.MjData(model)
    model.opt.gravity[:] = (0, 0, 0)

    root_x_jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "root_x")
    root_y_jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, "root_y")
    root_x_dof = model.jnt_dofadr[root_x_jid]
    root_y_dof = model.jnt_dofadr[root_y_jid]

    steps = int(round(args.seconds / model.opt.timestep))
    skip_steps = int(round(args.skip_seconds / model.opt.timestep))
    records = []
    cpg = HopfCPG(num_joints=6)
    ajoint_rad = degrees_to_radians(args.ajoint)
    cpg_params = HopfCPGParams(
        frequency=args.freq,
        wavelength=args.wavelength,
        ajoint=ajoint_rad,
        mu_scales=amp_scales_to_mu_scales(args.amp_scales),
        phase_lags=args.phase_lags,
        fb_phase=args.fb_phase,
        fb_amp=args.fb_amp,
    )

    for step in range(steps):
        data.ctrl[0:3] = 0.0
        targets = cpg.step(data.time, model.opt.timestep, cpg_params)
        data.ctrl[3:9] = np.clip(targets, -1.2, 1.2)
        mujoco.mj_step(model, data)

        # Negative tether effort estimates force generated by the swimmer.
        fx = -data.qfrc_actuator[root_x_dof]
        fy = -data.qfrc_actuator[root_y_dof]
        if step >= skip_steps:
            records.append((data.time, fx, fy, *data.ctrl[3:9]))

    arr = np.array(records, dtype=np.float64)
    fx = arr[:, 1]
    fy = arr[:, 2]
    force_mag = np.sqrt(fx**2 + fy**2)
    power_proxy = np.mean(np.square(arr[:, 3:9]))

    print("Tethered force measurement")
    print(f"  Hopf CPG: ajoint={args.ajoint:.3f} deg ({ajoint_rad:.3f} rad), freq={args.freq:.3f} Hz, wavelength={args.wavelength:.3f}, fb_phase={args.fb_phase:.3f}, fb_amp={args.fb_amp:.3f}")
    if args.amp_scales is not None:
        print("  amp scales:", ", ".join(f"{value:.3f}" for value in args.amp_scales))
    if args.phase_lags is not None:
        print("  phase lags:", ", ".join(f"{value:.3f}" for value in args.phase_lags))
    print(f"  samples={len(arr)}, skipped={args.skip_seconds:.2f}s")
    print(f"  mean Fx={np.mean(fx): .4f} N")
    print(f"  mean Fy={np.mean(fy): .4f} N")
    print(f"  |mean Fy|={abs(np.mean(fy)): .4f} N")
    print(f"  mean |Fy|={np.mean(np.abs(fy)): .4f} N")
    print(f"  mean |F|={np.mean(force_mag): .4f} N")
    print(f"  peak |F|={np.max(force_mag): .4f} N")
    print(f"  ctrl energy proxy={power_proxy: .4f}")

    if args.csv:
        args.csv.parent.mkdir(parents=True, exist_ok=True)
        with args.csv.open("w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["time", "force_x", "force_y", "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5", "ctrl6"])
            writer.writerows(records)
        print(f"  wrote {args.csv}")


if __name__ == "__main__":
    main()
